---
title: "Webscrape Train"
output: html_document
date: "2024-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(stringr)
library(xml2)
```

# Training 1
Testing on https://scrapeme.live/shop/ with the generated article from https://www.zenrows.com/blog/web-scraping-r#headless-browser-scraping

```{r}
document <- read_html("https://scrapeme.live/shop")

# selecting the list of product HTML elements 
html_product <- document %>% html_elements("li.product")
```

Breaking the data into its tags
```{r}
# # selecting the "a" HTML element storing the product URL 
# a_element <- html_product %>% html_element("a") 
# # selecting the "img" HTML element storing the product image 
# img_element <- html_product %>% html_element("img") 
# selecting the "h2" HTML element storing the product name 
h2_element <- html_product %>% html_element("h2") 
# # selecting the "span" HTML element storing the product price 
# span_element <- html_product %>% html_element("span")
```


## Extracting text 
https://www.youtube.com/watch?v=smriIBG08ok is the source, getting data out of our html object
```{r}
# Creates a vector of strings
temp = document %>% 
  html_nodes("h2") %>%
  html_text()
```
## Apartments example

```{r}
document <- read_html("https://www.apartments.com/boone-ia/2-bedrooms/")
doc <- as.character(document)
```

## Attempt using selenium

aid from https://www.youtube.com/watch?v=U1BrIPmhx10

```{r}
library(tidyverse)
library(RSelenium)
library(rvest)
library(httr)
library(stringr)
library(netstat)

rD <- rsDriver(verbose=FALSE)
rD <- remdr[["client"]]

# navigates the tab to firefox
remdr$navigate("https://www.apartments.com")
```

Parsing out the HTML we want

data will be stored in a variety of strings similar to: 

"<p class="property-pricing">$805 - 1,060</p>"

Get our full html
```{r}
Sys.sleep(5) # give the page time to fully load
html <- remDr$getPageSource()[[1]]
```

Parse out the prices
```{r}
# Use a regular expression to extract content between <p> tags
match <- str_match(html, '<p class="property-pricing">(.*?)<\\/p>')

if (!is.na(match[2])) {
  content_between_tags <- match[2]
  print(content_between_tags)
} else {
  print("No match found.")
}
```


